minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.0fecc75a64a39bc5600ff6a1cee8baff378a8cc1
  vitest: 4.1.9
  vite-plus: 0.0.0-commit.0fecc75a64a39bc5600ff6a1cee8baff378a8cc1
  '@vitest/coverage-v8': 4.1.9
